{% set name = "buildpy" %}
{% set version = "7.0.0" %}
{% set sha256 = "67a29424fc4760082d12d71e325dedcc75a371e13722515fa03f4733f8793b77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/84/cc/5e0285491b283c9a2e6eca6193a8ec6f0894d238f751af9dd4fda266f887/buildpy-7.0.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: true  # [win or py2k]

requirements:
  host:
    - boto3
    - google-cloud-bigquery
    - google-cloud-storage
    - pip
    - psutil
    - python
  run:
    - boto3
    - google-cloud-bigquery
    - google-cloud-storage
    - psutil
    - python

test:
  imports:
    - buildpy.vx

about:
  home: http://github.com/kshramt/{{ name }}
  license: GLP-3.0
  license_file: LICENSE.txt
  summary: 'A workflow engine in Python'

extra:
  recipe-maintainers:
    - kshramt
