{% set name = "buildpy" %}
{% set version = "6.2.5" %}
{% set sha256 = "9dc473129eebaeb16835d60737fdfbe16139971e4b5d9311a7cf066d33ccdb92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b7/a5/f5f89344a2fda80942d8da5b74ce652dcfdf8ad5e91667378548b3264a1e/buildpy-6.2.5.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: true  # [win or py2k]

requirements:
  host:
    - boto3
    - google-cloud-bigquery
    - google-cloud-storage
    - pip
    - psutil
    - python
  run:
    - boto3
    - google-cloud-bigquery
    - google-cloud-storage
    - psutil
    - python

test:
  imports:
    - buildpy.vx

about:
  home: http://github.com/kshramt/{{ name }}
  license: GLP-3.0
  license_file: LICENSE.txt
  summary: 'A workflow engine in Python'

extra:
  recipe-maintainers:
    - kshramt
