appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PbRNqJF5GTnTacW8XqsEoRDp2k2vSgmJvaBo0Nw1lnMCijiG1LSiOWRwA/nyNSko9Ym6TSd6+/wpxN0k9b7JDZ9bgueqDUwSVt2q5HKx3B+DDDKpaH7QzkQ1sykcAia0x8fwQoosdnyUDLbqudwfE6RbeS/rCfFuT3mSg2bTtIorbzoPrscR2p5PNdd5wwTmIsPeL48x7v4oF78Xgjz4rORgXOZg9WXVR6yo5KH84K8uB08aAU+v0kcg+WTbMfciIaNrZsMaIGHNphtwqkU/j6X7ka3j2CyAtNnm/p0GmjbE4sP7BkQrX1N4bBU7iTGEl3mBz9p6zl9wVNYvF742SLszLclTymIH3wJ4pywkGrH3zhwno8Sm0nGhAp+WjBE63NZ2fa/rHWXaqx9sPXNXIW8SaO59A5FBYtrMwzf2gQGSxdYBj6ouUevzbHf/uPrrnYNKS7xaHdKxLKHDhuPL48OgrsxY019i2BiKiMMZNWF7VftqvlFp+VuW5bFkOuA+fzHBZCHepe2aMBpN0I/5Qztpa3AdUfG6PtScN+3UEmWkOZL5SLQIqVS4InfL1RUSWMH/ygdjnm0uGBCbmHhoQD6qnULDO8ZRVs8rVtMJc9zoU9uikpmhRnTPgxLP48YeCpZiTWcChJlZPmr1X1HD4gG3kEOi4HN1dcY07OF0NgE=}
